### ISSUE TITLE
Review #1 - Cuando un jugador no elige mano, la jugada se define igual.

### ISSUE THREAD

**Issue by FacundoEG** [JoaquinGiacusa/desafio-modulo-6#1]
Hola Joaquin! como estas? primero que todo te felicito por haber terminado el desafío del modulo 6!

Te comento que estuve probando la webapp y funciona muy bien en lineas generales! , pero quería señalarte algunas cosas que note a modo de sugerencia que podrían mejorarse:

1. Fijate que cuando el otro jugador espera que presione "jugar", no muestra el nombre del contrincante que aun no esta listo:
![image](https://user-images.githubusercontent.com/79592789/151559856-be393962-37e7-4e8f-8949-654b2b11e97e.png)

2. Cuando no elegis ninguna mano, por alguna razon en la pantalla del user que si eligio una jugada se muestra la mano del contrincante (cuando el otro usuario no eligio nada al final) e inclusive se termina definiendo la jugada en base a eso, eso si te tendría que pedir que lo revises ya que podría traer conflictos en algun punto.
![image](https://user-images.githubusercontent.com/79592789/151560365-937fbe65-135e-4b5f-ade9-c67d34740a73.png)
![image](https://user-images.githubusercontent.com/79592789/151560468-ea1c3420-8866-4ef3-9c19-5d1e9b8edd04.png)
![image](https://user-images.githubusercontent.com/79592789/151560492-44c1b594-e8da-4b56-a0fe-e6513f3e754a.png)

Despues en todo lo demas lo veo super bien! asi que te pediría que revises eso de las jugadas nada mas!

Te mando un saludo y cualquier cosita podes consultarme por aca o mismo en el servidor de la carrera!

**Comment by JoaquinGiacusa** [comment]
Hola Facu. Gracias por la devolucion. Ahi lo pude acomodar creo.

**Comment by FacundoEG** [comment]
Te quedo buenisimo ahora Joaquin! se pudo resolver eso correctamente.

Te quería recomendar una cosita mas, por ejemplo aca si vos ya podes agarrar el error del endpoint, queda muy bien si usas algo textual para mostrarlo en el front asi el usuario sabe porque no puede avanzar!
![Screenshot_20220129_123317](https://user-images.githubusercontent.com/79592789/151666921-c8bc8e2c-f7a0-4ba5-ba49-856e05ab7771.png)

Voy a cerrar el issue porque ya se resolviste esa premisa, así que te dejo un saludo y te deseo suerte para el próximo modulo!
